name: Push translation updates to main branch

on:
  push:
    branches:
      - translations

jobs:
  update-PO:
    name: Update PO files
    runs-on: ubunto-latest
    steps:
      - name: Prepare the grounds
        uses: actions/checkout@v2
        run: sudo apt-get install git
        run: pip install mdpo
      - name: Create updated MD files
        run: po2md '_i18n/PO-files/*.po' 
