name: Work on main branch to pull new & updated translations from tf branch
# Run on main branch

on:
  push:
    branches:
      - 'translation-files'
    paths:
      - contribute-pages/**
      - documentation-pages/**
      - general-pages/**
      - general-strings/**
  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-PO:
    name: Generate & push translated files
    runs-on: ubuntu-latest
    steps:
        # Check out the repository and download it to the runner, allowing to run actions against the code
      - name: Get main repository
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Get translation repository
        uses: actions/checkout@v2
        with:
          ref: translation-files
          path: translation-files
      - run: git branch
      - run: ls -al
      - name: Install mdpo
        run: pip install mdpo
      - name: Set languages
        id: lang-set
        run: |
          languagelist=$(cat _config.yml | grep "languages: \[.*\]" )
          languagelist=${languagelist//[}
          languagelist=${languagelist//]}
          echo $languagelist
          languagelist=${languagelist//'languages: '}
          languagelist=${languagelist//,}
          # Exclude English (source) from list of languages to update
          languagelist=${languagelist//'en '}
          # Make variable consistent between steps
          echo "languages=$languagelist" >> $GITHUB_ENV
      - name: Print languages
        run: |
          languages=(${{ env.languages }})
          for language in "${languages[@]}"
          do echo $language
          done
      - name: Make Contribution pages
        run: |
          cd _i18n/en/contribute
          languages=(${{ env.languages }})
          for language in "${languages[@]}"
          do mkdir -p ../../$language/contribute
          done
          for file in *
          do
            for language in "${languages[@]}"
            do po2md $file --po-files ../../../translation-files/site-contribute_$language.PO --save ../../$language/contribute/$file
            git add ../../$language/contribute/$file
            done
          done
      - name: Make Documentation pages
        run: |
          cd _i18n/en/documentation
          ls
          languages=(${{ env.languages }})
          for language in "${languages[@]}"
          do mkdir -p ../../$language/documentation
          done
          for file in *
          do
            for language in "${languages[@]}"
            do po2md $file --po-files ../../../translation-files/site-documentation_$language.PO --save ../../$language/documentation/$file
            git add ../../$language/documentation/$file
            done
          done
      - name: Make General pages
        run: |
          cd _i18n/en/general
          ls
          languages=(${{ env.languages }})
          for language in "${languages[@]}"
          do mkdir -p ../../$language/general
          done
          for file in *
          do
            for language in "${languages[@]}"
            do po2md $file --po-files ../../../translation-files/site-general_$language.PO --save ../../$language/general/$file
            git add ../../$language/general/$file
            done
          done
      - name: Stage yml files
        run: |
          languages=(${{ env.languages }})
          for language in "${languages[@]}"
          do cp translation-files/general-strings/$language.yml _i18n/$language.yml
          git add _i18n/$language.yml
          done
      - name: Commit changes
        run: |
          git config user.name "AntennaPod Translations Bot"
          git config user.email "<bot@antennapod.org>"
          git status
          git commit -m "Update website with new translations"
          git push origin main
