name: Push new & updated translations to main branch
# Run on main branch

on:
  push:
    branches:
      - translation-files
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-PO:
    name: Generate & push translated files
    runs-on: ubuntu-latest
    steps:
        # checks out your repository and downloads it to the runner, allowing you to run actions against your code
      - uses: actions/checkout@v2
      - run: git fetch --depth=1
      - run: ls -al
      - name: Install mdpo
        run: pip install mdpo
      - name: Set languages
        run: |
          cat _config.yml
          languagelist=$(cat _config.yml | grep "languages: \[.*\]" )
          echo $languagelist
          languagelist=${languagelist//'languages: ['}
          echo $languagelist
          languagelist=${languagelist//]}
          echo $languagelist
          languagelist=${languagelist//,}
          echo $languagelist
          languages=($languagelist)
      - name: Print languages
        run: for value in "${languages[@]}"; do echo $value; done
      # name: Make General pages
