name: Push new & updated translations to main branch
# Run on main branch

on:
  push:
    branches:
      - translation-files
  push:
    branches:
      - main
    paths:
      - .github/workflows/translation-updates-to-main-repo.yml
  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-PO:
    name: Generate & push translated files
    runs-on: ubuntu-latest
    steps:
        # Check out the repository and download it to the runner, allowing to run actions against the code
      - uses: actions/checkout@v2
      - run: git fetch --depth=1
      - run: ls -al
      - name: Install mdpo
        run: pip install mdpo
      - name: Set languages
        id: lang-set
        run: |
          languagelist=$(cat _config.yml | grep "languages: \[.*\]" )
          languagelist=${languagelist//[}
          languagelist=${languagelist//]}
          echo $languagelist
          languagelist=${languagelist//'languages: '}
          languagelist=${languagelist//,}
          # Make variable consistent between steps
          echo "languages=$languagelist" >> $GITHUB_ENV
      - name: Print languages
        run: |
          languages=(${{ env.languages }})
          for language in "${languages[@]}"
          do echo $language
          done
# name: Make General pages
